# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_filter <- function(words, ifilename) {
    .Call(`_textprocessingDSI_rcpp_filter`, words, ifilename)
}

rcpp_join <- function(idir, ofilename, newline) {
    .Call(`_textprocessingDSI_rcpp_join`, idir, ofilename, newline)
}

rcpp_split <- function(fpath, odir, splitter, count) {
    .Call(`_textprocessingDSI_rcpp_split`, fpath, odir, splitter, count)
}

rcpp_summary <- function(ipath, delim) {
    .Call(`_textprocessingDSI_rcpp_summary`, ipath, delim)
}

